# Generated by Django 4.2.5 on 2023-09-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_date',
        ),
    ]
